name: Update DNS Records

on:
    push:
        branches:
            - main
            
jobs:
    dns:
        name: Update DNS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","accountid":"${{ secrets.CF_ID }}","apitoken":"${{ secrets.CF_TOKEN }}"}}' > ./creds.json
            
            - name: Push
              uses: is-cool-me/dnscontrol-action@4.8.2
              env:
                CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
              with:
                args: push
                config_file: 'dnsconfig.js'